### ISSUE TITLE
Deleting tower on map appear again

### ISSUE THREAD

**Issue by olkitu** [CellMapper/Cellmapper-Site#17]
This bug confirmed

**Comment by zivan56** [comment]
Please confirm it is still an issue as of right now going foward.

**Comment by mrk2005** [comment]
It is. Actually, I cannot even delete towers.. "Delete successfull", but the tower is still here.

**Comment by zivan56** [comment]
That is a different bug that only affected the EU mirror.  It would eventually be deleted, it would not come back by itself like the bug in this ticket.
If the tower comes back, then it is this bug the ticket is for.  From what I've heard from others, its been fixed by only have 1 server generate data instead of 2.
